language: python

matrix:
  include:
    - python: pypy
    - python: pypy3
    - python: 2.7
    - python: 3.5
    - python: 3.6
    - python: 3.7
    - python: 3.8
      dist: xenial
      sudo: true

install:
  - python setup.py -q install

script:
  - python setup.py -q test
